### ISSUE TITLE
pre-processing: extract gene from genome

### ISSUE THREAD

**Issue by tkosciol** [biocore/microprot#11]
input: Prodigal `faa` file
output: `fasta` file with a single gene or list of genes, name of gene

read n-th or all genes from the genome file.

**Comment by mortonjt** [comment]
You may be already familiar with this, but there is a function in samtools called [fai_fetch](http://samtools.sourceforge.net/samtools/faidx/Functions/Functions.html) that can fetch sequences in a genome via fasta index.

**Comment by tkosciol** [comment]
this is done now, right?

**Comment by qiyunzhu** [comment]
@tkosciol Yes it is!
