### ISSUE TITLE
pre-processing script: generate PDB100

### ISSUE THREAD

**Issue by tkosciol** [biocore/microprot#12]
take `pdb_seqres.txt` and a set of representative structures from PDB RESTful WebService, e.g. `http://www.rcsb.org/pdb/rest/representatives?cluster=100`
and generate `pdb_100.txt` including only headers and sequences from representative clusters.

Reference data is available on Barnacle in: `/projects/microprot/dbs/pdb`

The script should have an option to generate sequences at other clustering levels, e.g. 70% (`pdb_70.txt`).

**Comment by tkosciol** [comment]
@qiyunzhu can you take a look at this, now? It should be quick and easy!

**Comment by qiyunzhu** [comment]
@tkosciol This is already done, in `processing.py`.

**Comment by tkosciol** [comment]
@qiyunzhu damn! you're quick! ;) I need to find a new issue for you, then!
