### ISSUE TITLE
MMSeqs2 install

### ISSUE THREAD

**Issue by tkosciol** [biocore/microprot#28]
we need to build MMSeqs2 (https://github.com/soedinglab/mmseqs2), as instructed in the repo.
Currently, it is here: `/projects/microprot/tools/MMseqs2`

On barnacle it currently does not compile. Jeff had a look into it and he replied:
```
You will need to try the avx2 static version.  
It is installing cluster wide, even though you could have unpacked to local directory.  
Module is created for it as well.  We can readdress install and compilation at a later time. 
```

**Comment by sjanssen2** [comment]
here is a way to compile it on barnacle:
1) download the current source from github
2) edit file cmake/CheckSSEFeatures.cmake by replacing `-march=native` by `-march=corei7`
3) compile as described in the README
