### ISSUE TITLE
split sequence

### ISSUE THREAD

**Issue by tkosciol** [biocore/microprot#4]
take sequence and output from parser and split sequence according to the parser result.
e.g. sequence: NP001.fasta; residues=(40, 60), source='PDB')
output: NP001_1-39.fasta, NP001_61-100.fasta, NP_001_40-60_PDB.fasta

requirements:
* needs to be able to cope with discontinuous (multiple) boundaries
* needs to have space for heuristics (e.g. if 2 domains separated by less than 5 residues, treat them as 1 domain)
* should annotate sequence in header accordingly (name, residues, source (if threshold met), version pointer, program+version, timestamp, MSA size (if source='MSA'))

**Comment by sjanssen2** [comment]
Sounds similar to what my function `report_uncovered_subsequences` in  microprot/scripts/pdb_search.py does. What is missing is the creation to files + the annotation with these additional information of point 3.
I feel that we need to have this function in place for all kinds of parses, thus we should think about a standard data type (= class) how to report hits.

**Comment by tkosciol** [comment]
@sjanssen2 agreed. this should definitely go into a class, eventually. For now, maybe we should bash out another parser to see how to generalize it reasonably?

**Comment by sjanssen2** [comment]
totally agree on this strategy!

**Comment by qiyunzhu** [comment]
Sounds good!

**Comment by tkosciol** [comment]
OK, based on `Sankefile` scaffold I wrote, it would be great to have 2 Python functions: `split_sequence`, `mask_sequence`

```
mask_sequence(out_fp, split_list_fp, **params)
'''
input:
    out_fp : filepath to HHblits/HHsearch output
    split_list_fp: filepath to output of the script; list of splits
    params : prob value cutoff, E-value cutoff, minimum fragment length
returns:
    writes a file with identified from to boundaries, e.g.
        1 52
        103 160
        161 250
'''
```

```
split_sequence(fasta_fp, split_list)
input:
    fasta_fp : filepath to fasta sequence file
    split_list : output of `mask_sequence` script
returns:
    domain_boundaries, domain
    domain_boundaries : tuple of (start, end) of each domain identified by `mask_sequence`
    domain : sequence of the identified domain (str)
```

**Comment by sjanssen2** [comment]
I am just starting to understand what this should do. And my major concern right now is the disconnect between the out_fp and the fasta_fp files, which is only necessary if we really need to produce split_list_fp and forget everything else we know about those hits to than read them in again from fasta_fp, albeit these information are already in out_fp.

Thus, my suggestion is to merge those two functions into one which might write split_list_fp as a byproduct.

**Comment by tkosciol** [comment]
I totally agree from purely software design point of view.
Just the thing here is, that `mask_sequence` lives in different rule than `split_sequence`, thus we need an intermediate file to do this.

**Comment by sjanssen2** [comment]
do we want to obtain those parts of the query sequence that are not covered by the hits or the hit-subsequences ?!?
