### ISSUE TITLE
secondary structure and disorder predictions

### ISSUE THREAD

**Issue by tkosciol** [biocore/microprot#8]
run secondary structure and disorder predictions.
Modify scripts to use a single MSA for both (if possible).

secondary structure: PSIPRED
disorder: DISOPRED3
Programs available in `tools/`.

write outputs to: `results/ss` and `results/disorder`, respectively.
Stretches of disorder should be removed from subsequent analyses (>= 15 residues?).

**Comment by tkosciol** [comment]
I also added MEMSAT-SVM for transmembrane topology predictions. Should follow the same scheme as PSIPRED and DISOPRED.

NOTE: by default, MEMSAT-SVM uses a slightly different set of parameters than both PSIPRED and DISOPRED. Would be useful to test if it matters, or if we can use the same `mtx` file for all.

**Comment by tkosciol** [comment]
To rephrase the problem: each program, i.e. PSIPRED, DISOPRED3 and MEMSAT-SVM has its own wrapper (`runpsipred`, `run_disopred.pl`, `run_memsat-svm.pl`)which runs PSI-BLAST and then the main program itself. We want to split each into 2 - run PSI-BLAST and run PSIPRED/DISPRED/MEMSAT-SVM. As a result we would need to run PSI-BLAST only once and then use the output as an input for all of those 3 programs.

**Comment by tkosciol** [comment]
As a side-note, we can also use the same PSI-BLAST predictions to use as input for domain splitting! 😃

**Comment by qiyunzhu** [comment]
@tkosciol Great job!

**Comment by sjanssen2** [comment]
I see two separate problems here: 1) running PSI-BLAST for our input sequence 2) find a way to let the following programs start from the PSI-BLAST result rather than from the original input.

In the following, I will take notes how to accomplish 2):
- [x] MEMSAT-SVM: invoke the program with the option `-mtx 1` and make sure that the input file is a PSI-BLAST result
- [ ] PSIPRED
- [ ] DISOPRED3
- [ ] domain splitting

**Comment by sjanssen2** [comment]
@tkosciol are different parameters for blastpgp a problem for recycling intermediate results?

**Comment by tkosciol** [comment]
The differences are cosmetic, really, and shouldn't impact the predictions. I'd use the set of params which is specified with PSIPRED.
We care the least about MEMSAT-SVM results and this program has slightly different params than psipred and disopred

On Feb 15, 2017, at 15:55, Stefan Janssen <notifications@github.com<mailto:notifications@github.com>> wrote:


@tkosciol<https://github.com/tkosciol> are different parameters for blastpgp a problem for recycling intermediate results?

**Comment by sjanssen2** [comment]
regarding PSIPRED, which of the following two script are we going to run `runpsipred` or `runpsipred_single`, i.e. which one do I need to hack?

**Comment by tkosciol** [comment]
'runpsipred' (i.e. full version)
single does not use sequence profile.

**Comment by sjanssen2** [comment]
I push a PR with a patch for psipred, but we might want to come up with a more convenient way to distribute third party software which we patch ... maybe we can have our own conda recipes?

**Comment by sjanssen2** [comment]
@tkosciol do we already know which program to use for domain splitting?

**Comment by tkosciol** [comment]
Still working on it! Should know by the end of the week.

t.

**Comment by sjanssen2** [comment]
We have now three packages on biocore for the three programs PSIPRED, DISOPRED, MEMSAT-SVM. Install them as follows `conda install -c biocore memsat-svm disopred psipred`, you might need to add biocore as an anaconda channel `conda config --add channels bioconda`.

All three programs should have the same command line arguments to re-use pre-computed PSI-BLAST results. Raise the flag -mtx=1 and use your psi-blast result file as input file. Furthermore, there is no longer the need to manually change any path names in the wrapper programs. Everything should be configurable by arguments.

@tkosciol please check if the programs actually compute what we expect.

**Comment by tkosciol** [comment]
@sjanssen2 can I close this issue? We're removing domain splitting from this bundle.

**Comment by sjanssen2** [comment]
Yes, but you might want to save the documentation like previous post from me - maybe in a wiki?

**Comment by tkosciol** [comment]
@sjanssen2 all of your comments should be saved in a wiki for future generations ;)
wiki here: https://github.com/biocore/microprot/wiki
